# Generated by Django 5.0 on 2024-01-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_alter_profile_recommended_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
